spring:
  profiles:
    active: peer2
  application:
    name: eureka-server

---
spring:
    profiles: peer1
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/
---
spring:
    profiles: peer2
server:
  port: 1112
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/